version: 2
updates:

    - package-ecosystem: "maven"
      directory: "/"
      schedule:
          interval: "daily"
      assignees:
          - "nmondal"

    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
          interval: "daily"
      assignees:
          - "nmondal"
