name: Spark Framework CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '1.8', '1.9', '1.10', '1.11' ]
    name: Java Version ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          check-latest: true
          cache: 'maven'
      - run: ./mvnw test
